### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by ultrasaurus** [ultrasaurus/irc-tokio#5]
I would value some advice here.  What are best practices either for Rust in general or Tokio specifically

**Comment by hwchen** [comment]
I think that at the beginning stages of a project, returning `Box<dyn std::error::Error>` is fine. And your fns that return that return `std::io::Error` are fine, if that's the only error any of the internal calls return. When the application gets more complex, you could use a library that provides a dynamic Error type which also conveniently adds context and handles backtraces. I prefer [anyhow](https://github.com/dtolnay/anyhow), though there's definitely many options out there. A [survey](https://blog.yoshuawuyts.com/error-handling-survey/#libraries).

For me, the question at the moment is whether you want to introduce a custom error for errors that come from parsing `Message`. At the moment, it just returns an `Option` but it's hard to know how parsing failed. If I were doing this, I'd use [thiserror](https://github.com/dtolnay/thiserror) to help with boilerplate. But it's probably good to derive `Error` manually for your error enum manually first if you haven't before.

So overall, I see two error handling tracks, each with a basic strategy and a library-enabled strategy.
- dynamic (for apps, gathering errors to report) -> use `Box<dyn std::error::Error>` and then `anyhow`.
- specific/custom (for library-like, to report up specific errors) -> manually derive `std::error::Error` for custom defined error, then use `thiserror` for boilerplate of deriving.

[link](https://blog.burntsushi.net/rust-error-handling/) for how to implement error handling yourself. (this would be the specific/custom path). I think some people use this path without the dynamic path, if you're willing to write out a lot of error variants.

All strategies should combine well with tokio. Let me know if any of this needs clarifying.

**Comment by ultrasaurus** [comment]
Since our goal is to create a tutorial around this and this example is destined to be tokio sample code, I think we should avoid additional dependencies (though for my personal learning, love the links --- thank you!)

Perhaps a good next step would be to write some Message tests for error handling, maybe including a custom error.  Here's the detail on valid messages:  https://tools.ietf.org/html/rfc2812#section-2.3

Some errors that could be good starters:
- MissingCommand:  empty string or a prefix with no "command" (e.g. a string that has no spaces and starts with a `:`)
- StringTooLong: IRC Message limit is 512 characters

**Comment by hwchen** [comment]
Keeping dependencies to a minimum makes a lot of sense.

I'm not sure how much you want me to write :) but I'm happy to take a crack at errors/tests for `Message`

**Comment by ultrasaurus** [comment]
Pull request welcome!
