### ISSUE TITLE
consider changing Session fields from &str to String

### ISSUE THREAD

**Issue by ultrasaurus** [ultrasaurus/irc-tokio#7]
feedback from https://github.com/ultrasaurus/irc-tokio/pull/4

> You use &str for nick and label in your LineHandler and Session structs; I think that this may complicate lifetimes down the road for not much gain. I don't think it hurts for these structs to own their label and nick data and I don't think there's much any performance gain in referencing. Using &str does make sense for Message though.

I think it makes sense to use `String` in Session

**Comment by ultrasaurus** [comment]
I experimented with changing Protocol struct field `nick` (previously Session struct) to be a `String` which seemed to make it more cumbersome to use, since I would have to add `.to_string` in some places when calling it.  

@hwchen I'm going to close this for now, but if I'm not understanding the benefit of the suggestion feel free to illustrate with a PR.  Or maybe I'll see the light after working with the code for a while.  

Closing for now, but please re-open if you have more thoughts on this topic!

**Comment by hwchen** [comment]
Hey, it's totally fine not to change. I'm not sure that at this level it will make that much of a difference. I just wanted to clarify, since you mentioned having to use `to_string`. I have a draft PR to illustrate that the way I changed it, you don't have to use `to_string`.
